//! R6 — THE FULL FUNCTIONAL E2E: a REAL subprocess agent CLI doing REAL work, GOVERNED + GATED +
//! EVIDENCED, on an ON-DISK shared estate store, distributed by a REAL council verdict.
//!
//! Everything here is real except that the wrapped CLI + council voters are deterministic shell
//! scripts (fake-but-real: genuine subprocesses doing genuine fs work + honoring the genuine
//! governance hook) so the test is hermetic + offline. The on-disk `brain.db` is shared by
//! governance + orchestration + council + agent, and the per-tool-call pre-hook is a real child
//! process that opens that SAME on-disk store and gates the wrapped CLI across the process boundary.
//!
//! We prove, end-to-end:
//!   (clean unit)  the wrapped CLI's real subprocess WRITES a real file (`out.txt`); the unit-level
//!                 governance gate ALLOWS; the per-tool-call hook ALLOWS; phase → `Approved`;
//!                 the real artifact + evidence land on the shared store. FILE EXISTS on disk.
//!   (secret unit) the unit's work embeds `AKIA…`; the per-tool-call hook DENIES the write (exit 2);
//!                 the wrapped CLI aborts → the forbidden file is NEVER written; phase → `Rejected`.
//!                 FILE IS ABSENT on disk.
//!   (persistence) ALL entities — session, both units, the claim(s), both phases, the approved
//!                 unit's output, AND the council task + verdict — persist on the ONE on-disk store,
//!                 read back via a FRESH `SqliteStore::open(path)` connection (cross-handle sharing).

#![cfg(unix)]

use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::time::Duration;

use wicked_agent::{run_session_wrapped, scope::EntityMode, GovernanceMode};
use wicked_apps_core::{
    synthetic_symbol, GraphRead, NodeKind, SqliteStore, AGENT_SESSION, CLI_RANKING,
    CONFORMANCE_CLAIM, COUNCIL_TASK, COUNCIL_VERDICT, PHASE, WORK_UNIT,
};
use wicked_council::{AgenticCli, Category, Confidence, InputMode};
use wicked_governance::{register_policy, Effect, Policy, Severity, Trigger};

/// An AWS access key id shaped to trip the deny policy's regex (`AKIA[0-9A-Z]{16}`).
const SECRET: &str = "AKIAIOSFODNN7EXAMPLE";

/// A unique temp dir for one test run.
fn unique_tempdir(tag: &str) -> PathBuf {
    use std::sync::atomic::{AtomicU64, Ordering};
    static N: AtomicU64 = AtomicU64::new(0);
    let n = N.fetch_add(1, Ordering::Relaxed);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let dir =
        std::env::temp_dir().join(format!("wa-full-{tag}-{}-{nanos}-{n}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("create tempdir");
    dir
}

/// A deny policy that fires whenever the evaluated context embeds an AWS access key id. Selected for
/// BOTH unit phases (`unit-1`, `unit-2`) so the gate fires on each — its `contains` trigger only
/// matches the unit whose work carries the secret.
fn deny_secrets_policy() -> Policy {
    Policy {
        id: "pol-deny-secrets".to_string(),
        kind: "security".to_string(),
        applies_to: vec!["unit-1".to_string(), "unit-2".to_string()],
        effect: Effect::Deny,
        trigger: Trigger {
            contains: Some("AKIA[0-9A-Z]{16}".to_string()),
        },
        obligations: vec![],
        criteria: "no aws access keys in the unit's work".to_string(),
        severity: Severity::High,
        rule: "Deny any unit whose work embeds an AWS access key id.".to_string(),
    }
}

/// Point the emit seam at a guaranteed-missing bus + a temp dead-letter spool (hermetic events).
fn hermetic_emit(dir: &Path) -> PathBuf {
    let spool = dir.join("emit-deadletter.ndjson");
    unsafe {
        std::env::set_var(
            wicked_apps_core::emit::EMIT_PROGRAM_ENV,
            "wicked-bus-absent-xyzzy-9000",
        );
        std::env::set_var(wicked_apps_core::emit::DEADLETTER_ENV, &spool);
    }
    spool
}

/// Write the FAKE-BUT-REAL wrapped CLI: a genuine shell script that (1) reads its TASK.txt work
/// order, (2) decides what to write — like a real agent embedding credentials, a "deploy script"
/// task produces content carrying an AWS key (the secret is generated by the CLI at tool-call time,
/// NOT present in the unit description, so the per-tool-call hook is what catches it), (3) HONORS the
/// per-tool-call governance hook — it pipes the proposed tool-call JSON into `$WICKED_PRETOOL_HOOK`
/// and only performs the REAL write if the hook exits 0 (a non-zero exit = DENY ⇒ it aborts the
/// write, the forbidden file is never created), and (4) emits the tool-call as a JSON line on stdout
/// so the harness can evaluate + capture it. It writes `out.txt` in its sandbox cwd — REAL fs work.
fn write_wrapped_cli(dir: &Path) -> String {
    let path = dir.join("fake-agent.sh");
    // The script is the wrapped-CLI contract: `fake-agent.sh <TASK.txt>`. A "deploy script" task
    // makes the agent embed an AWS key into the content it proposes to write — the realistic
    // tool-call the per-tool-call hook must catch (the unit description has no literal key).
    // `__SECRET__` is substituted with the AWS-key literal (avoids format!-escaping the shell).
    let script = r#"#!/bin/sh
set -eu
TASK_FILE="$1"
TASK="$(cat "$TASK_FILE")"
OUT="out.txt"
# The agent decides the file CONTENT. A "deploy script" task => it embeds a (fake) AWS key — exactly
# the credential-leak a real agent would commit, and the thing the per-tool-call hook must deny.
case "$TASK" in
  *deploy*) CONTENT="export AWS_ACCESS_KEY_ID=__SECRET__ && deploy --prod" ;;
  *)        CONTENT="$TASK" ;;
esac
# The proposed tool-call: write CONTENT to out.txt. The hook decides over THIS JSON (esp. content).
CALL=$(printf '{"tool":"write_file","path":"%s","content":"%s"}' "$OUT" "$CONTENT")
# Consult the per-tool-call governance hook BEFORE acting (if one is wired).
ALLOW=1
if [ -n "${WICKED_PRETOOL_HOOK:-}" ]; then
  if printf '%s' "$CALL" | "$WICKED_PRETOOL_HOOK" >/dev/null 2>&1; then
    ALLOW=1
  else
    ALLOW=0
  fi
fi
# Always surface the tool-call so the harness can evaluate it + (on allow) capture the artifact.
printf '{"tool_call":{"tool":"write_file","path":"%s","content":"%s"}}\n' "$OUT" "$CONTENT"
if [ "$ALLOW" = "1" ]; then
  # REAL filesystem work: write the genuine artifact.
  printf '%s' "$CONTENT" > "$OUT"
  echo "wrote $OUT"
else
  # DENIED by the hook — the destructive effect NEVER happens; report it honestly.
  echo "BLOCKED: pretool hook denied the write of $OUT" >&2
  exit 3
fi
"#
    .replace("__SECRET__", SECRET);
    std::fs::write(&path, script).expect("write wrapped cli");
    let mut perms = std::fs::metadata(&path).expect("stat").permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&path, perms).expect("chmod");
    path.display().to_string()
}

/// Write an executable fake-but-real council VOTER script that echoes the four scaffold lines,
/// recommending `recommendation` (a roster seat key) — a genuine subprocess the REAL council
/// dispatcher spawns + parses, producing a REAL (non-degraded) verdict.
fn write_voter(dir: &Path, name: &str, recommendation: &str) -> String {
    let path = dir.join(name);
    let script = format!(
        "#!/bin/sh\n\
         echo \"RECOMMENDATION: {recommendation}\"\n\
         echo \"TOP_RISK: latency\"\n\
         echo \"CHANGE_MY_MIND: depends on the benchmark\"\n\
         echo \"DISQUALIFIER: None\"\n"
    );
    std::fs::write(&path, script).expect("write voter");
    let mut perms = std::fs::metadata(&path).expect("stat").permissions();
    perms.set_mode(0o755);
    std::fs::set_permissions(&path, perms).expect("chmod");
    path.display().to_string()
}

/// An `AgenticCli` roster record. The wrapped CLI contract is `command <TASK.txt>`, so the
/// `headless_invocation` is just the script path (no `{PROMPT}` — the launcher appends TASK.txt).
fn cli_record(key: &str, script_path: &str) -> AgenticCli {
    AgenticCli {
        key: key.to_string(),
        display_name: format!("Fake {key}"),
        binary: script_path.to_string(),
        headless_invocation: script_path.to_string(),
        category: Category::AgenticCoder,
        input_mode: InputMode::PromptArg,
        version_probe: vec![],
        trust_flags: vec![],
        alt_binaries: vec![],
        confidence: Confidence::Verified,
        enabled_for_council: true,
    }
}

/// THE R6 PROOF: a real wrapped-CLI subprocess does real fs work under a real governance gate, on an
/// ON-DISK shared store, distributed by a REAL council verdict. Clean unit writes a file + approves;
/// secret unit's write is BLOCKED by the per-tool-call hook (file absent) + rejected; and ALL
/// entities (incl. council task + verdict) read back from a FRESH on-disk connection.
#[test]
fn full_functional_e2e_real_cli_governed_gated_on_disk_shared_store() {
    let dir = unique_tempdir("e2e");
    let spool = hermetic_emit(&dir);

    // ── The ONE shared ON-DISK store: brain.db (WAL, multi-connection). ──
    let db_path = dir.join("brain.db");
    let db_str = db_path.display().to_string();

    // The gate-hook child process opens this SAME on-disk store; the in-process engine and the hook
    // must agree. Export the DB path (the hook reads WICKED_ESTATE_DB) and point the hook at the
    // REAL built wicked-agent binary (the test's current_exe is the test harness, not the binary).
    let agent_bin = env!("CARGO_BIN_EXE_wicked-agent");
    unsafe {
        std::env::set_var("WICKED_ESTATE_DB", &db_str);
        std::env::set_var("WICKED_AGENT_BIN", agent_bin);
    }

    // Register the DENY policy on the on-disk shared store (governance writes here, in-process).
    {
        let mut store = SqliteStore::open(&db_path).expect("open on-disk brain.db");
        register_policy(&mut store, &deny_secrets_policy()).expect("register deny policy");
    } // drop this handle: the harness opens its OWN handle next (proves cross-handle on disk).

    // The fake-but-real wrapped CLI + two REAL council voters (both recommend "agent-a").
    let wrapped = write_wrapped_cli(&dir);
    let va = write_voter(&dir, "voter-a.sh", "agent-a");
    let vb = write_voter(&dir, "voter-b.sh", "agent-a");
    // The roster: the launchable wrapped CLI (the seat the council assigns) + the two voters. The
    // council weighs WHICH seat owns each unit; both voters name "agent-a" → a non-degraded verdict.
    let roster = vec![
        cli_record("agent-a", &wrapped),
        cli_record("voter-a", &va),
        cli_record("voter-b", &vb),
    ];

    // A 2-unit problem. NOTE: neither unit DESCRIPTION contains a literal AWS key — so the
    // unit-level gate ALLOWS both launches. Unit-1 asks for a "deploy script": the wrapped CLI
    // embeds an AWS key into the content it proposes to write, and the PER-TOOL-CALL hook catches it
    // (deny ⇒ the CLI aborts the write). Unit-2 ("release notes") is clean end-to-end.
    let problem = "Write the production deploy script to out. Write the release notes to out.";

    // The harness opens its OWN on-disk handle (a SECOND connection to brain.db) and runs the real
    // wrapped-CLI path with the per-tool-call pretool hook mechanism.
    let sandbox = dir.join("sandbox");
    let result = {
        let mut store = SqliteStore::open(&db_path).expect("harness opens on-disk brain.db");
        run_session_wrapped(
            &mut store,
            roster,
            problem,
            EntityMode::Shared,
            Some("sess-r6"),
            GovernanceMode::PretoolHook,
            &sandbox,
            Duration::from_secs(30),
        )
        .expect("run_session_wrapped on the on-disk shared store")
    }; // drop the harness handle: every read-back below uses a FRESH connection.

    // ── The session ran over exactly two units; one approved, one rejected. ──
    assert_eq!(
        result.units.len(),
        2,
        "the problem decomposes into two units"
    );
    assert_eq!(result.approved, 1, "exactly the clean unit approves");
    assert_eq!(result.rejected, 1, "exactly the secret unit is rejected");

    let unit1 = &result.units[0]; // secret
    let unit2 = &result.units[1]; // clean

    // The council produced a REAL (non-degraded) assignment to a roster seat for each unit.
    assert!(
        !unit1.assigned_cli.is_empty() && !unit2.assigned_cli.is_empty(),
        "the council assigned a CLI to each unit"
    );

    // ── (secret unit) the PER-TOOL-CALL hook DENIED the write → blocked, deny claim, phase rejected.
    // The wrapped CLI WAS launched (unit-level gate allowed; description has no literal key); the
    // hook caught the AWS key in the proposed tool-call content and the CLI aborted (exit 3). ──
    assert!(
        unit1.gate_blocked,
        "unit-1's write was BLOCKED by the per-tool-call hook (the effect never landed)"
    );
    assert_eq!(
        unit1.decision.as_deref(),
        Some("deny"),
        "the per-tool-call hook's claim is a Deny (the authoritative gate decision)"
    );
    assert_eq!(
        unit1.phase_status, "rejected",
        "the deny drove unit-1's orchestration phase to rejected (ADR-0003)"
    );
    assert!(!unit1.approved, "a blocked unit is NEVER approved");

    // ── REAL FILESYSTEM STATE: the forbidden file is ABSENT on disk. ──
    let unit1_out = sandbox.join("sess-r6").join(&unit1.unit_id).join("out.txt");
    assert!(
        !unit1_out.exists(),
        "the per-tool-call hook BLOCKED the write — the forbidden file must NOT exist at {}",
        unit1_out.display()
    );

    // ── (clean unit) the real subprocess wrote a real file; phase approved. ──
    assert_eq!(
        unit2.phase_status, "approved",
        "the clean unit's phase is approved"
    );
    assert!(unit2.approved);
    assert_eq!(
        unit2.cli_exit_code,
        Some(0),
        "the clean wrapped-CLI subprocess exited 0 (real exit code), got {:?}",
        unit2.cli_exit_code
    );

    // ── REAL FILESYSTEM STATE: the clean unit's file EXISTS, with the real content the CLI wrote. ──
    let unit2_out = sandbox.join("sess-r6").join(&unit2.unit_id).join("out.txt");
    assert!(
        unit2_out.exists(),
        "the approved unit's real subprocess wrote a real file at {}",
        unit2_out.display()
    );
    let written = std::fs::read_to_string(&unit2_out).expect("read the real artifact");
    assert!(
        written.contains("release notes"),
        "the real artifact carries the clean task content, got {written:?}"
    );

    // The clean unit's real exit was 0; the secret unit's wrapped CLI aborted non-zero (exit 3).
    assert_eq!(
        unit1.cli_exit_code,
        Some(3),
        "the secret wrapped-CLI subprocess aborted non-zero after the hook deny, got {:?}",
        unit1.cli_exit_code
    );

    // ── PERSISTENCE: read EVERYTHING back via a FRESH SqliteStore::open(path) connection. ──
    // This proves cross-handle sharing on disk: a brand-new connection sees all the writes the
    // harness (a different connection) and the council (its own connection) committed.
    let fresh = SqliteStore::open(&db_path).expect("FRESH on-disk connection for read-back");

    // The session node.
    let session = wicked_agent::get_session(&fresh, "sess-r6")
        .expect("read session")
        .expect("session node persists on the on-disk store");
    assert_eq!(session.id, "sess-r6");

    // Both work-unit nodes with their final status + claim ids.
    let units = wicked_agent::session_units(&fresh, "sess-r6").expect("read units");
    assert_eq!(
        units.len(),
        2,
        "both work-unit nodes persist on the on-disk store"
    );
    assert_eq!(units[0].status, wicked_agent::UnitStatus::Rejected);
    assert_eq!(units[1].status, wicked_agent::UnitStatus::Done);
    assert!(
        units
            .iter()
            .all(|u| u.conformance_ref.is_some() && u.assigned_cli.is_some()),
        "each unit node carries its claim id + council assignment"
    );

    // The ConformanceClaim node for the deny (durable evidence of WHY unit-1 was rejected).
    let deny_claim_id = unit1.claim_id.as_deref().expect("unit-1 minted a claim");
    let claim_node = fresh
        .get_node(&synthetic_symbol(CONFORMANCE_CLAIM, deny_claim_id))
        .expect("get_node ok")
        .expect("the deny ConformanceClaim node persists on the on-disk store");
    let recovered = wicked_governance::claim_from_node(&claim_node).expect("decode claim");
    assert_eq!(recovered.decision, wicked_apps_core::Decision::Deny);

    // Both phase nodes persist with the resolved status; the rejected one carries the Deny veto.
    let phase1 = wicked_orchestration::get_phase(&fresh, &unit1.phase_id)
        .expect("get phase 1")
        .expect("unit-1 phase node persists");
    let phase2 = wicked_orchestration::get_phase(&fresh, &unit2.phase_id)
        .expect("get phase 2")
        .expect("unit-2 phase node persists");
    assert_eq!(phase1.status, wicked_orchestration::PhaseStatus::Rejected);
    assert_eq!(phase1.gate_decision, Some(wicked_apps_core::Decision::Deny));
    assert_eq!(phase2.status, wicked_orchestration::PhaseStatus::Approved);

    // The work-output node exists ONLY for the approved unit, and carries the REAL artifact metadata.
    assert!(
        wicked_agent::execute::get_work_output(&fresh, &unit1.unit_id)
            .unwrap()
            .is_none(),
        "the REJECTED unit recorded NO work-output node"
    );
    let out2 = wicked_agent::execute::get_work_output(&fresh, &unit2.unit_id)
        .unwrap()
        .expect("the APPROVED unit recorded a work-output node on the on-disk store");
    assert_eq!(
        out2.metadata.get("real_cli").and_then(|v| v.as_bool()),
        Some(true),
        "the output node records that a REAL CLI produced it"
    );
    assert_eq!(
        out2.metadata.get("exit_code").and_then(|v| v.as_i64()),
        Some(0),
        "the output node records the real subprocess exit code"
    );

    // ── The COUNCIL task + verdict also persist on the ONE on-disk store (read via the fresh conn). ──
    // The council mirrors its task/verdict to estate nodes; assert at least one of each exists, and
    // that a verdict decodes (the REAL synthesized verdict that produced the assignment).
    for (kind, at_least) in [
        (AGENT_SESSION, 1usize),
        (WORK_UNIT, 2),
        (PHASE, 2),
        (CONFORMANCE_CLAIM, 1),
        (COUNCIL_TASK, 1),
        (COUNCIL_VERDICT, 1),
        (CLI_RANKING, 1),
    ] {
        let q = wicked_estate_core::SymbolQuery {
            kinds: vec![NodeKind::Other(kind.to_string())],
            ..Default::default()
        };
        let found = fresh.find_symbols(&q).expect("find_symbols ok");
        assert!(
            found.len() >= at_least,
            "expected ≥{at_least} {kind} node(s) on the ONE on-disk store, found {}",
            found.len()
        );
    }
    // Decode one verdict to prove it is a real synthesized council verdict (not an empty shell).
    let verdict_q = wicked_estate_core::SymbolQuery {
        kinds: vec![NodeKind::Other(COUNCIL_VERDICT.to_string())],
        ..Default::default()
    };
    let verdict_nodes = fresh.find_symbols(&verdict_q).expect("find verdicts");
    let verdict =
        wicked_council::store::verdict_from_node(&verdict_nodes[0]).expect("decode verdict");
    assert!(
        verdict.winning_recommendation.is_some(),
        "the council produced a real winning recommendation (non-degraded)"
    );

    // Cleanup.
    unsafe {
        std::env::remove_var("WICKED_ESTATE_DB");
        std::env::remove_var("WICKED_AGENT_BIN");
        std::env::remove_var(wicked_apps_core::emit::EMIT_PROGRAM_ENV);
        std::env::remove_var(wicked_apps_core::emit::DEADLETTER_ENV);
    }
    let _ = std::fs::remove_file(&spool);
    let _ = std::fs::remove_dir_all(&dir);
}
